//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckRequests.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class check_request_audit
    {
        public int Id { get; set; }
        public System.DateTime create_date { get; set; }
        public int create_by { get; set; }
        public string xml_trace { get; set; }
        public int check_request { get; set; }
    
        public virtual check_request check_request1 { get; set; }
    }
}
