//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckRequests.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class check_detail
    {
        public int check_id { get; set; }
        public string check_number { get; set; }
        public int buy_type { get; set; }
        public System.DateTime check_date { get; set; }
        public decimal total_amount { get; set; }
        public string status { get; set; }
        public string image_path { get; set; }
        public string merged_file_path { get; set; }
    }
}
