//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckRequests.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class check_request_detail
    {
        public int id { get; set; }
        public int check_request { get; set; }
        public int media_order { get; set; }
        public Nullable<int> action { get; set; }
        public Nullable<System.DateTime> action_date { get; set; }
        public Nullable<int> auth_user { get; set; }
        public string notes { get; set; }
        public System.DateTime last_update_date { get; set; }
        public int last_update_by { get; set; }
        public Nullable<int> media_order_detail { get; set; }
    
        public virtual check_request check_request1 { get; set; }
        public virtual check_request_action check_request_action { get; set; }
        public virtual employee employee { get; set; }
        public virtual media_order media_order1 { get; set; }
    }
}
