//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckRequests.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.check_request_detail = new HashSet<check_request_detail>();
        }
    
        public string employee_code { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string social_security_num { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string employee_designation { get; set; }
        public Nullable<int> department { get; set; }
        public string addr_1 { get; set; }
        public string addr_2 { get; set; }
        public string state_code { get; set; }
        public string city_name { get; set; }
        public string zip_code { get; set; }
        public string phone_1 { get; set; }
        public string phone_2 { get; set; }
        public string employee_email { get; set; }
        public string note { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> last_update_date { get; set; }
        public Nullable<int> last_update_by { get; set; }
        public System.DateTime create_date { get; set; }
        public int create_by { get; set; }
        public int id { get; set; }
        public Nullable<bool> visual_status { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string fax_num { get; set; }
        public string country { get; set; }
        public string ext_num { get; set; }
        public string office { get; set; }
        public Nullable<System.DateTime> last_role_update_date { get; set; }
        public Nullable<int> primary_assistant { get; set; }
        public Nullable<int> b_prcent { get; set; }
        public string byrid { get; set; }
        public string b_cvia { get; set; }
        public string b_alsosee { get; set; }
        public Nullable<int> oldmts_id { get; set; }
        public Nullable<System.DateTime> last_locked_date { get; set; }
        public string permanent_id { get; set; }
        public string temporary_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<check_request_detail> check_request_detail { get; set; }
    }
}
